#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIM.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PIM")]
	public partial class ChamadosDALDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHAMADO(CHAMADO instance);
    partial void UpdateCHAMADO(CHAMADO instance);
    partial void DeleteCHAMADO(CHAMADO instance);
    #endregion
		
		public ChamadosDALDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PIMConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChamadosDALDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChamadosDALDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChamadosDALDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChamadosDALDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHAMADO> CHAMADOs
		{
			get
			{
				return this.GetTable<CHAMADO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHAMADO")]
	public partial class CHAMADO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _DEPARTAMENTO;
		
		private int _GRAU_URGENCIA;
		
		private string _ANDAR;
		
		private string _EQUIPAMENTO;
		
		private string _DESCRICAO;
		
		private int _CLIENTE;
		
		private System.Nullable<int> _FUNCIONARIO;
		
		private System.Nullable<System.TimeSpan> _CONCLUSAO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDEPARTAMENTOChanging(int value);
    partial void OnDEPARTAMENTOChanged();
    partial void OnGRAU_URGENCIAChanging(int value);
    partial void OnGRAU_URGENCIAChanged();
    partial void OnANDARChanging(string value);
    partial void OnANDARChanged();
    partial void OnEQUIPAMENTOChanging(string value);
    partial void OnEQUIPAMENTOChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnCLIENTEChanging(int value);
    partial void OnCLIENTEChanged();
    partial void OnFUNCIONARIOChanging(System.Nullable<int> value);
    partial void OnFUNCIONARIOChanged();
    partial void OnCONCLUSAOChanging(System.Nullable<System.TimeSpan> value);
    partial void OnCONCLUSAOChanged();
    #endregion
		
		public CHAMADO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTAMENTO", DbType="Int NOT NULL")]
		public int DEPARTAMENTO
		{
			get
			{
				return this._DEPARTAMENTO;
			}
			set
			{
				if ((this._DEPARTAMENTO != value))
				{
					this.OnDEPARTAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DEPARTAMENTO = value;
					this.SendPropertyChanged("DEPARTAMENTO");
					this.OnDEPARTAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRAU_URGENCIA", DbType="Int NOT NULL")]
		public int GRAU_URGENCIA
		{
			get
			{
				return this._GRAU_URGENCIA;
			}
			set
			{
				if ((this._GRAU_URGENCIA != value))
				{
					this.OnGRAU_URGENCIAChanging(value);
					this.SendPropertyChanging();
					this._GRAU_URGENCIA = value;
					this.SendPropertyChanged("GRAU_URGENCIA");
					this.OnGRAU_URGENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANDAR", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ANDAR
		{
			get
			{
				return this._ANDAR;
			}
			set
			{
				if ((this._ANDAR != value))
				{
					this.OnANDARChanging(value);
					this.SendPropertyChanging();
					this._ANDAR = value;
					this.SendPropertyChanged("ANDAR");
					this.OnANDARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQUIPAMENTO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EQUIPAMENTO
		{
			get
			{
				return this._EQUIPAMENTO;
			}
			set
			{
				if ((this._EQUIPAMENTO != value))
				{
					this.OnEQUIPAMENTOChanging(value);
					this.SendPropertyChanging();
					this._EQUIPAMENTO = value;
					this.SendPropertyChanged("EQUIPAMENTO");
					this.OnEQUIPAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLIENTE", DbType="Int NOT NULL")]
		public int CLIENTE
		{
			get
			{
				return this._CLIENTE;
			}
			set
			{
				if ((this._CLIENTE != value))
				{
					this.OnCLIENTEChanging(value);
					this.SendPropertyChanging();
					this._CLIENTE = value;
					this.SendPropertyChanged("CLIENTE");
					this.OnCLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUNCIONARIO", DbType="Int")]
		public System.Nullable<int> FUNCIONARIO
		{
			get
			{
				return this._FUNCIONARIO;
			}
			set
			{
				if ((this._FUNCIONARIO != value))
				{
					this.OnFUNCIONARIOChanging(value);
					this.SendPropertyChanging();
					this._FUNCIONARIO = value;
					this.SendPropertyChanged("FUNCIONARIO");
					this.OnFUNCIONARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONCLUSAO", DbType="Time")]
		public System.Nullable<System.TimeSpan> CONCLUSAO
		{
			get
			{
				return this._CONCLUSAO;
			}
			set
			{
				if ((this._CONCLUSAO != value))
				{
					this.OnCONCLUSAOChanging(value);
					this.SendPropertyChanging();
					this._CONCLUSAO = value;
					this.SendPropertyChanged("CONCLUSAO");
					this.OnCONCLUSAOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
