/******************************************/
-- LIMPA SCHEMA
/******************************************/

-- DROPA CONSTRAINTS

IF OBJECT_ID('FK_DEPARTAMENTO_SETOR') IS NOT NULL
	ALTER TABLE DEPARTAMENTO DROP CONSTRAINT FK_DEPARTAMENTO_SETOR

IF OBJECT_ID('FK_CLIENTE_DEPARTAMENTO') IS NOT NULL
	ALTER TABLE CLIENTE DROP CONSTRAINT FK_CLIENTE_DEPARTAMENTO

IF OBJECT_ID('FK_FUNCIONARIO_DEPARTAMENTO') IS NOT NULL
	ALTER TABLE FUNCIONARIO DROP CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO
PRINT 'DROP CONSTRAINTS'

-- DROPA TABLES

IF OBJECT_ID('SETOR') IS NOT NULL
	DROP TABLE SETOR

IF OBJECT_ID('DEPARTAMENTO') IS NOT NULL
	DROP TABLE DEPARTAMENTO

IF OBJECT_ID('GRAU_URGENCIA') IS NOT NULL
	DROP TABLE GRAU_URGENCIA

IF OBJECT_ID('CLIENTE') IS NOT NULL
	DROP TABLE CLIENTE

IF OBJECT_ID('FUNCIONARIO') IS NOT NULL
	DROP TABLE FUNCIONARIO

IF OBJECT_ID('CHAMADO') IS NOT NULL
	DROP TABLE CHAMADO
PRINT 'DROP TABLES'

/******************************************/
-- CRIA TABLES
/******************************************/
	
CREATE TABLE SETOR
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE DEPARTAMENTO
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SETOR INT
);

CREATE TABLE GRAU_URGENCIA
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTE
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	DEPARTAMENTO INT NOT NULL
	--SETOR INT NOT NULL,
);

CREATE TABLE FUNCIONARIO
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	DEPARTAMENTO INT NOT NULL
);

CREATE TABLE CHAMADO
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DEPARTAMENTO INT NOT NULL,
	GRAU_URGENCIA INT NOT NULL,
	ANDAR VARCHAR(10) NOT NULL,
	EQUIPAMENTO VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	CLIENTE INT NOT NULL,
	FUNCIONARIO INT NULL,
	CONCLUSAO TIME
);
PRINT 'CREATE TABLES'

/******************************************/
-- CRIA CONSTRAINTS
/******************************************/

ALTER TABLE DEPARTAMENTO	ADD CONSTRAINT FK_DEPARTAMENTO_SETOR		FOREIGN KEY	(SETOR)			REFERENCES SETOR(ID)
ALTER TABLE CLIENTE			ADD CONSTRAINT FK_CLIENTE_DEPARTAMENTO		FOREIGN KEY	(DEPARTAMENTO)	REFERENCES DEPARTAMENTO(ID)
ALTER TABLE FUNCIONARIO		ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO	FOREIGN KEY (DEPARTAMENTO)	REFERENCES DEPARTAMENTO(ID)
PRINT 'CREATE CONSTRAINTS'

/******************************************/
-- POPULA TABLES
/******************************************/
PRINT CHAR(13)+'POPULA TABLES'
SET NOCOUNT ON

SET IDENTITY_INSERT SETOR ON

INSERT INTO SETOR(ID, NOME) VALUES (1, 'Administrativo')
INSERT INTO SETOR(ID, NOME) VALUES (2, 'Recursos Humanos')
INSERT INTO SETOR(ID, NOME) VALUES (3, 'Financeiro')
INSERT INTO SETOR(ID, NOME) VALUES (4, 'Tecnologia')
INSERT INTO SETOR(ID, NOME) VALUES (5, 'Operacional')

SET IDENTITY_INSERT SETOR OFF

PRINT CHAR(9)+'-SETOR'

SET IDENTITY_INSERT DEPARTAMENTO ON
INSERT INTO DEPARTAMENTO(ID, NOME, SETOR) VALUES (1, 'Teste', 1)
INSERT INTO DEPARTAMENTO(ID, NOME, SETOR) VALUES (2, 'Manutençao', 4)
INSERT INTO DEPARTAMENTO(ID, NOME, SETOR) VALUES (3, 'Compras', 5)
INSERT INTO DEPARTAMENTO(ID, NOME, SETOR) VALUES (4, 'Vendas', 5)
SET IDENTITY_INSERT DEPARTAMENTO Off

SET NOCOUNT OFF

PRINT CHAR(9)+'-DEPARTAMENTO'