CREATE TABLE SETOR
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE DEPARTAMENTO
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SETOR INT
);

CREATE TABLE GRAU_URGENCIA
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTE
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	DEPARTAMENTO INT NOT NULL
	--SETOR INT NOT NULL,
);

CREATE TABLE FUNCIONARIO
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	DEPARTAMENTO INT NOT NULL
);

CREATE TABLE CHAMADO
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	DEPARTAMENTO INT NOT NULL,
	GRAU_URGENCIA INT NOT NULL,
	ANDAR VARCHAR(10) NOT NULL,
	EQUIPAMENTO VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	CLIENTE INT NOT NULL,
	FUNCIONARIO INT NULL,
	CONCLUSAO TIME
);


