CREATE TABLE SETOR
(
	ID INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_SETOR PRIMARY KEY (ID)
);

CREATE TABLE DEPARTAMENTO
(
	ID INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SETOR INT,
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID)
);

CREATE TABLE GRAU_URGENCIA
(
	ID INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_GRAU_URGENCIA PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE
(
	ID INT NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	DEPARTAMENTO INT NOT NULL,
	--SETOR INT NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

CREATE TABLE FUNCIONARIO
(
	ID INT NOT NULL,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(16) NOT NULL,
	DEPARTAMENTO INT NOT NULL,
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID)
);

CREATE TABLE CHAMADO
(
	ID INT NOT NULL,
	DEPARTAMENTO INT NOT NULL,
	GRAU_URGENCIA INT NOT NULL,
	ANDAR VARCHAR(10) NOT NULL,
	EQUIPAMENTO VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(500) NOT NULL,
	CLIENTE INT NOT NULL,
	FUNCIONARIO INT NULL,
	CONCLUSAO TIME,
	CONSTRAINT PK_CHAMADO PRIMARY KEY (ID)
);


